name = "xeta-pay-dashboard"
main = "worker/index.ts"
compatibility_date = "2024-03-01"

[[d1_databases]]
binding = "DB"
database_name = "xetapay-db"
database_id = "95f7261a-5f1e-4e49-b35c-24f4962bb29d"
migrations_dir = "migrations"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "BRIDGE_STORE"
id = "9465f88bd89443ea981b3e6e30a76397"
