name = "xeta-pay-dashboard"
main = "worker/index.ts"
compatibility_date = "2024-03-01"

[[d1_databases]]
binding = "DB"
database_name = "xeta-pay-db"
database_id = "3863efc8-a787-46e3-87b9-4555264e18d6"
migrations_dir = "migrations"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "BRIDGE_STORE"
id = "9465f88bd89443ea981b3e6e30a76397"
